### ISSUE TITLE
GTMAppAuthDriveExampleiOS/Pods/AppAuth/Source/iOS/OIDAuthorizationUICoordinatorIOS.h:58:12: Parameter 'presentingViewController' not found in the function declaration

### ISSUE THREAD

**Issue by timeflying** [google/GTMAppAuth#26] opened 2017-04-16 16:31 UTC
I  just following the steps:
```
target 'GTMAppAuth Drive Example iOS' do
  platform :ios, '8.0'

  pod 'GTMAppAuth'
  pod 'GoogleAPIClientForREST/Drive'
end
```
$ pod install
$ open Example-iOS.xcworkspace
Copy the client ID to the clipboard from google console.
In GTMAppAuthExampleViewController.m update kClientID with new client id.

Finally, open Info.plist and fully expand "URL types" (a.k.a. "CFBundleURLTypes") and replace com.googleusercontent.apps.YOUR_CLIENT with the reverse DNS notation form of your client id (not including the :/oauthredirect path component).

But
Why error in the comment ?
Xcode 8.3.1
<img width="1012" alt="2017-04-17 12 15 56" src="https://cloud.githubusercontent.com/assets/6119146/25072532/34df9862-2303-11e7-81ce-157fe5cb23e2.png">

**Comment by jostster** [comment] 2017-04-18 20:55
Duplicate of #21

**Closed** 2017-04-19 13:05 UTC
