### ISSUE TITLE
Support Carthage.

### ISSUE THREAD

**Issue by aaroncrespo** [google/GTMAppAuth#24] opened 2017-04-14 05:17 UTC
Supporting Carthage would go a long way for making this Library easier to use in Swift and iOS in general. Many project might not allow cocoapods.

**Comment by petea** [comment] 2019-03-05 21:56
Duplicate of #40

**Closed** 2019-03-05 21:56 UTC
Labels: Triaged, enhancement, help wanted

**Comment by HsmdiBodic** [comment] 2019-07-29 12:51
PLEX

**Comment by HsmdiBodic** [comment] 2019-07-29 12:52
PS3PLEXVT
