### ISSUE TITLE
Update usage of deprecated methods

### ISSUE THREAD

**Issue by Idomo** [google/GTMAppAuth#119] opened 2021-04-03 11:46 UTC
![image](https://user-images.githubusercontent.com/26777129/113477445-653fa680-948a-11eb-8ffe-6da3ee8e09ab.png)
Also AppAuth have deprecation usage that they've fixed in https://github.com/openid/AppAuth-iOS/pull/246
You may update it too.
![image](https://user-images.githubusercontent.com/26777129/113477599-a97f7680-948b-11eb-8219-329642f234e6.png)

**Comment by petea** [comment] 2021-04-03 15:09
Duplicate of #105

**Closed** 2021-04-03 15:09 UTC
