### ISSUE TITLE
Invalid request: could not determine client_id from request

### ISSUE THREAD

**Issue by guidedways** [google/GTMAppAuth#64] opened 2018-04-08 11:20 UTC
I'm sorry for cross posting this issue, but this is quite serious. We saw this come up a few days ago on the mac and now it's on iOS. We haven't updated the iOS app in 10 months so we know it isn't us. We've found a workaround for now but please can someone from Google investigate this? This is giving a lot of users a lot of inconvenience.

Kindly see details of the issue and a resolution in this thread here:

https://github.com/openid/AppAuth-iOS/issues/226

Summary: Google's OAuth request handling no longer processes client_id / client_secret properly when sent as an `Authorization` HTTP header. The solution is to send these as POST parameters.

**Comment by WilliamDenniss** [comment] 2018-04-09 21:57
Google's iOS app OAuth client type doesn't use client secrets, only the Mac one does.  So on iOS, you shouldn't be using client secret, which means the Authorization HTTP header wouldn't be used at all.

When you register the OAuth client, select "iOS" for the iOS client, and "Other" for the Desktop (macOS) one, following the [docs](https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-Google.md).

**Comment by WilliamDenniss** [comment] 2018-04-09 21:57
Closing this as a dupe of the AppAuth-iOS bug

**Closed by WilliamDenniss** 2018-04-09 21:57 UTC
