### ISSUE TITLE
Crashed calling any method after login

### ISSUE THREAD

**Issue by zlstt** [google/GTMAppAuth#1] opened 2016-11-22 03:23 UTC
*** Terminating app due to uncaught exception 'Attempted to create a token refresh request from a token response with no refresh token.', reason: 'Attempted to create a token refresh request from a token response with no refresh token.'
When run the Drive Sample, it crashed by calling fetchFileList ([service executeQuery:query
completionHandler:^(GTLRServiceTicket *callbackTicket,
GTLRDrive_FileList *fileList,
NSError *callbackError) { ) :

**Comment by WilliamDenniss** [comment] 2016-11-22 17:37
Dupe of https://github.com/google/google-api-objectivec-client-for-rest/issues/67

**Closed by WilliamDenniss** 2016-11-22 17:37 UTC
